### ISSUE TITLE
Do you have any plans for designing a web user interface?

### ISSUE THREAD

**Issue by yuzebin** [dibrale/samist#3]
Do you have plans to design a web user interface, or do you have any suggestions on how to run this tool on a GPU server?

**Comment by dibrale** [comment]
Hello @yuzebin,

To run SAMIST on a GPU server, start the script from a command line interface that supports X11 forwarding. You can then interact with the GUI using an X server (e.g.: [Xming](https://sourceforge.net/projects/xming/) if you are using Windows) on the machine you are connecting from.

I have no plans at this time for creating a SAMIST webui, but the project is open to contributions. My consulting company, ADMC Science and Consulting, is also open to orders for custom software that can meet your needs.

**Comment by yuzebin** [comment]
Thank you for taking the time to provide such a comprehensive response. I am extremely grateful.
